### ISSUE TITLE
CONTRIBUITING

### ISSUE THREAD

**Issue by AlmeidaJoao** [nozotrox/blockchain-practice-projects#3]
As an open-source repository, I would advise creating a CONTRIBUTING file to help your project contributors do good work, instead of repeating the contributing text on every markdown file.

**Comment by nozotrox** [comment]
As an open-source newbie, I take your advice. What if we just leave the CONTRIBUTING in the cover readme file?

**Comment by AlmeidaJoao** [comment]
Everyone has their start, I did not get what you meant exactly but, here is a link that might help: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by nozotrox** [comment]
Nvm, I'm just excited to start.
Thanks for sharing. I'll lool it up.
